import { Navigate, createBrowserRouter } from 'react-router-dom';
import { AppShell } from './components/layout/AppShell';
import { HomePage, PublicStudySetDetailPage, SearchStudySetsPage, SearchUsersPage } from './pages/PublicPages';
import { ChangePasswordPage, EditProfilePage, ForgotPasswordPage, LoginPage, ProfilePage, RegisterPage, ResetPasswordPage } from './pages/AuthProfilePages';
import {
  AvailableExamsPage,
  ExamInfoPage,
  ExamResultPage,
  FlashcardStudyPage,
  JoinClassPage,
  LearnerClassDetailPage,
  LearnerClassesPage,
  LearnerDashboardPage,
  LearnerProgressPage,
  LearnerStudySetDetailPage,
  LearnerStudySetsPage,
  QuizResultPage,
  ReviewWrongAnswersPage,
  StudySetQuizPage,
  TakeExamPage,
} from './pages/LearnerPages';
import {
  AssignStudySetPage,
  ClassInvitationPage,
  ClassMembersPage,
  CreateClassPage,
  JoinRequestsPage,
  TeacherClassDetailPage,
  TeacherClassesPage,
  TeacherDashboardPage,
} from './pages/TeacherClassPages';
import {
  AiGenerateQuestionsPage,
  CreateQuestionBankPage,
  CreateQuestionPage,
  EditQuestionBankPage,
  EditQuestionPage,
  ImportErrorsPage,
  ImportPreviewPage,
  ImportQuestionsPage,
  QuestionBankDetailPage,
  QuestionBanksPage,
} from './pages/QuestionBankPages';
import {
  ConfigureExamPage,
  CreateExamSessionPage,
  CreateStudySetPage,
  MonitorExamSessionPage,
  TeacherExamInfoPage,
  TeacherExamsPage,
} from './pages/TeacherStudyExamPages';
import {
  AccessDeniedPage,
  AdminDashboardPage,
  AdminUserDetailPage,
  AdminUsersPage,
  AnalyticsPage,
  ExportReportPage,
  NotFoundPage,
  NotificationsPage,
  PaymentResultPage,
  PremiumPlansPage,
  ResourceManagementPage,
  SystemStatusPage,
  UpgradePremiumPage,
} from './pages/OtherPages';

export const router = createBrowserRouter([
  {
    path: '/',
    element: <AppShell />,
    children: [
      { index: true, element: <HomePage /> },
      { path: 'search/study-sets', element: <SearchStudySetsPage /> },
      { path: 'search/users', element: <SearchUsersPage /> },
      { path: 'sets/:id/public', element: <PublicStudySetDetailPage /> },
      { path: 'auth/register', element: <RegisterPage /> },
      { path: 'auth/login', element: <LoginPage /> },
      { path: 'auth/forgot-password', element: <ForgotPasswordPage /> },
      { path: 'auth/reset-password', element: <ResetPasswordPage /> },
      { path: 'profile', element: <ProfilePage /> },
      { path: 'profile/edit', element: <EditProfilePage /> },
      { path: 'profile/change-password', element: <ChangePasswordPage /> },
      { path: 'learner/dashboard', element: <LearnerDashboardPage /> },
      { path: 'learner/classes', element: <LearnerClassesPage /> },
      { path: 'learner/classes/join', element: <JoinClassPage /> },
      { path: 'learner/classes/:id', element: <LearnerClassDetailPage /> },
      { path: 'learner/study-sets', element: <LearnerStudySetsPage /> },
      { path: 'learner/study-sets/:id', element: <LearnerStudySetDetailPage /> },
      { path: 'learner/study-sets/:id/flashcards', element: <FlashcardStudyPage /> },
      { path: 'learner/study-sets/:id/quiz', element: <StudySetQuizPage /> },
      { path: 'learner/study-sets/:id/result', element: <QuizResultPage /> },
      { path: 'learner/study-sets/:id/review', element: <ReviewWrongAnswersPage /> },
      { path: 'learner/progress', element: <LearnerProgressPage /> },
      { path: 'learner/exams', element: <AvailableExamsPage /> },
      { path: 'learner/exams/:id/info', element: <ExamInfoPage /> },
      { path: 'learner/exams/:id/take', element: <TakeExamPage /> },
      { path: 'learner/exams/:id/result', element: <ExamResultPage /> },
      { path: 'teacher/dashboard', element: <TeacherDashboardPage /> },
      { path: 'teacher/classes', element: <TeacherClassesPage /> },
      { path: 'teacher/classes/create', element: <CreateClassPage /> },
      { path: 'teacher/classes/:id', element: <TeacherClassDetailPage /> },
      { path: 'teacher/classes/:id/invitation', element: <ClassInvitationPage /> },
      { path: 'teacher/classes/:id/members', element: <ClassMembersPage /> },
      { path: 'teacher/classes/:id/join-requests', element: <JoinRequestsPage /> },
      { path: 'teacher/classes/:id/assign-study-set', element: <AssignStudySetPage /> },
      { path: 'teacher/question-banks', element: <QuestionBanksPage /> },
      { path: 'teacher/question-banks/create', element: <CreateQuestionBankPage /> },
      { path: 'teacher/question-banks/:id', element: <QuestionBankDetailPage /> },
      { path: 'teacher/question-banks/:id/edit', element: <EditQuestionBankPage /> },
      { path: 'teacher/question-banks/:id/questions/create', element: <CreateQuestionPage /> },
      { path: 'teacher/question-banks/:id/questions/:questionId/edit', element: <EditQuestionPage /> },
      { path: 'teacher/question-banks/:id/import', element: <ImportQuestionsPage /> },
      { path: 'teacher/question-banks/:id/import/errors', element: <ImportErrorsPage /> },
      { path: 'teacher/question-banks/:id/import/preview', element: <ImportPreviewPage /> },
      { path: 'teacher/question-banks/:id/ai-generate', element: <AiGenerateQuestionsPage /> },
      { path: 'teacher/study-sets/create', element: <CreateStudySetPage /> },
      { path: 'teacher/exams', element: <TeacherExamsPage /> },
      { path: 'teacher/exams/create', element: <CreateExamSessionPage /> },
      { path: 'teacher/exams/:id/configure', element: <ConfigureExamPage /> },
      { path: 'teacher/exams/:id/info', element: <TeacherExamInfoPage /> },
      { path: 'teacher/exams/:id/monitor', element: <MonitorExamSessionPage /> },
      { path: 'teacher/analytics', element: <AnalyticsPage /> },
      { path: 'teacher/reports/export', element: <ExportReportPage /> },
      { path: 'premium', element: <PremiumPlansPage /> },
      { path: 'premium/upgrade', element: <UpgradePremiumPage /> },
      { path: 'premium/payment-result', element: <PaymentResultPage /> },
      { path: 'admin/dashboard', element: <AdminDashboardPage /> },
      { path: 'admin/users', element: <AdminUsersPage /> },
      { path: 'admin/users/:id', element: <AdminUserDetailPage /> },
      { path: 'admin/resources', element: <ResourceManagementPage /> },
      { path: 'admin/system-status', element: <SystemStatusPage /> },
      { path: 'notifications', element: <NotificationsPage /> },
      { path: 'access-denied', element: <AccessDeniedPage /> },
      { path: 'not-found', element: <NotFoundPage /> },
      { path: '*', element: <Navigate to='/not-found' replace /> },
    ],
  },
]);
