import { Navigate, createBrowserRouter } from 'react-router-dom';
import type { ReactNode } from 'react';
import { AllowGuestOrRole, RequireRole } from './auth/RequireRole';
import { AppShell } from './components/layout/AppShell';
import { HomePage, PublicStudySetDetailPage, SearchStudySetsPage, SearchUsersPage } from './pages/PublicPages';
import { ChangePasswordPage, EditProfilePage, ForgotPasswordPage, LoginPage, ProfilePage, RegisterPage, ResetPasswordPage } from './pages/AuthProfilePages';
import {
  AvailableExamsPage,
  ExamInfoPage,
  ExamResultPage,
  FlashcardStudyPage,
  JoinClassPage,
  LearnerClassDetailPage,
  LearnerClassesPage,
  LearnerDashboardPage,
  LearnerProgressPage,
  LearnerStudySetDetailPage,
  LearnerStudySetsPage,
  QuizResultPage,
  ReviewWrongAnswersPage,
  StudySetQuizPage,
  TakeExamPage,
} from './pages/LearnerPages';
import {
  AssignStudySetPage,
  ClassInvitationPage,
  ClassMembersPage,
  CreateClassPage,
  JoinRequestsPage,
  TeacherClassDetailPage,
  TeacherClassesPage,
  TeacherDashboardPage,
} from './pages/TeacherClassPages';
import {
  AiGenerateQuestionsPage,
  CreateQuestionBankPage,
  CreateQuestionPage,
  EditQuestionBankPage,
  EditQuestionPage,
  ImportErrorsPage,
  ImportPreviewPage,
  ImportQuestionsPage,
  QuestionBankDetailPage,
  QuestionBanksPage,
} from './pages/QuestionBankPages';
import {
  ConfigureExamPage,
  CreateExamSessionPage,
  CreateStudySetPage,
  MonitorExamSessionPage,
  TeacherExamInfoPage,
  TeacherExamsPage,
  TeacherStudySetsPage,
} from './pages/TeacherStudyExamPages';
import {
  AccessDeniedPage,
  AdminDashboardPage,
  AdminUserDetailPage,
  AdminUsersPage,
  AnalyticsPage,
  ExportReportPage,
  NotFoundPage,
  NotificationsPage,
  PaymentResultPage,
  PremiumPlansPage,
  ResourceManagementPage,
  SystemStatusPage,
  UpgradePremiumPage,
} from './pages/OtherPages';

const learnerOnly = (element: ReactNode) => <RequireRole allowed={['Learner']}>{element}</RequireRole>;
const teacherOnly = (element: ReactNode) => <RequireRole allowed={['Teacher']}>{element}</RequireRole>;
const adminOnly = (element: ReactNode) => <RequireRole allowed={['Admin']}>{element}</RequireRole>;
const authenticatedOnly = (element: ReactNode) => <RequireRole allowed={['Learner', 'Teacher', 'Admin']}>{element}</RequireRole>;
const premiumActorOnly = (element: ReactNode) => <RequireRole allowed={['Learner', 'Teacher']}>{element}</RequireRole>;
const publicOrPremiumActor = (element: ReactNode) => <AllowGuestOrRole allowed={['Learner', 'Teacher']}>{element}</AllowGuestOrRole>;

export const router = createBrowserRouter([
  {
    path: '/',
    element: <AppShell />,
    children: [
      { index: true, element: <HomePage /> },
      { path: 'search/study-sets', element: <SearchStudySetsPage /> },
      { path: 'search/users', element: <SearchUsersPage /> },
      { path: 'sets/:id/public', element: <PublicStudySetDetailPage /> },
      { path: 'auth/register', element: <RegisterPage /> },
      { path: 'auth/login', element: <LoginPage /> },
      { path: 'auth/forgot-password', element: <ForgotPasswordPage /> },
      { path: 'auth/reset-password', element: <ResetPasswordPage /> },
      { path: 'sets/:id/flashcards', element: <FlashcardStudyPage /> },
      { path: 'profile', element: authenticatedOnly(<ProfilePage />) },
      { path: 'profile/edit', element: authenticatedOnly(<EditProfilePage />) },
      { path: 'profile/change-password', element: authenticatedOnly(<ChangePasswordPage />) },
      { path: 'profile/reset-password', element: authenticatedOnly(<ResetPasswordPage />) },
      { path: 'learner/dashboard', element: learnerOnly(<LearnerDashboardPage />) },
      { path: 'learner/classes', element: learnerOnly(<LearnerClassesPage />) },
      { path: 'learner/classes/join', element: learnerOnly(<JoinClassPage />) },
      { path: 'learner/classes/:id', element: learnerOnly(<LearnerClassDetailPage />) },
      { path: 'learner/study-sets', element: learnerOnly(<LearnerStudySetsPage />) },
      { path: 'learner/study-sets/:id', element: learnerOnly(<LearnerStudySetDetailPage />) },
      { path: 'learner/study-sets/:id/flashcards', element: learnerOnly(<FlashcardStudyPage />) },
      { path: 'learner/study-sets/:id/quiz', element: learnerOnly(<StudySetQuizPage />) },
      { path: 'learner/study-sets/:id/result', element: learnerOnly(<QuizResultPage />) },
      { path: 'learner/study-sets/:id/review', element: learnerOnly(<ReviewWrongAnswersPage />) },
      { path: 'learner/progress', element: learnerOnly(<LearnerProgressPage />) },
      { path: 'learner/exams', element: learnerOnly(<AvailableExamsPage />) },
      { path: 'learner/exams/:id/info', element: learnerOnly(<ExamInfoPage />) },
      { path: 'learner/exams/:id/take', element: learnerOnly(<TakeExamPage />) },
      { path: 'learner/exams/:id/result', element: learnerOnly(<ExamResultPage />) },
      { path: 'teacher/dashboard', element: teacherOnly(<TeacherDashboardPage />) },
      { path: 'teacher/classes', element: teacherOnly(<TeacherClassesPage />) },
      { path: 'teacher/classes/create', element: teacherOnly(<CreateClassPage />) },
      { path: 'teacher/classes/:id', element: teacherOnly(<TeacherClassDetailPage />) },
      { path: 'teacher/classes/:id/invitation', element: teacherOnly(<ClassInvitationPage />) },
      { path: 'teacher/classes/:id/members', element: teacherOnly(<ClassMembersPage />) },
      { path: 'teacher/classes/:id/join-requests', element: teacherOnly(<JoinRequestsPage />) },
      { path: 'teacher/classes/:id/assign-study-set', element: teacherOnly(<AssignStudySetPage />) },
      { path: 'teacher/question-banks', element: teacherOnly(<QuestionBanksPage />) },
      { path: 'teacher/question-banks/create', element: teacherOnly(<CreateQuestionBankPage />) },
      { path: 'teacher/question-banks/:id', element: teacherOnly(<QuestionBankDetailPage />) },
      { path: 'teacher/question-banks/:id/edit', element: teacherOnly(<EditQuestionBankPage />) },
      { path: 'teacher/question-banks/:id/questions/create', element: teacherOnly(<CreateQuestionPage />) },
      { path: 'teacher/question-banks/:id/questions/:questionId/edit', element: teacherOnly(<EditQuestionPage />) },
      { path: 'teacher/question-banks/:id/import', element: teacherOnly(<ImportQuestionsPage />) },
      { path: 'teacher/question-banks/:id/import/errors', element: teacherOnly(<ImportErrorsPage />) },
      { path: 'teacher/question-banks/:id/import/preview', element: teacherOnly(<ImportPreviewPage />) },
      { path: 'teacher/question-banks/:id/ai-generate', element: teacherOnly(<AiGenerateQuestionsPage />) },
      { path: 'teacher/study-sets', element: teacherOnly(<TeacherStudySetsPage />) },
      { path: 'teacher/study-sets/create', element: teacherOnly(<CreateStudySetPage />) },
      { path: 'teacher/exams', element: teacherOnly(<TeacherExamsPage />) },
      { path: 'teacher/exams/create', element: teacherOnly(<CreateExamSessionPage />) },
      { path: 'teacher/exams/:id/configure', element: teacherOnly(<ConfigureExamPage />) },
      { path: 'teacher/exams/:id/info', element: teacherOnly(<TeacherExamInfoPage />) },
      { path: 'teacher/exams/:id/monitor', element: teacherOnly(<MonitorExamSessionPage />) },
      { path: 'teacher/analytics', element: teacherOnly(<AnalyticsPage />) },
      { path: 'teacher/reports/export', element: teacherOnly(<ExportReportPage />) },
      { path: 'premium', element: publicOrPremiumActor(<PremiumPlansPage />) },
      { path: 'premium/upgrade', element: premiumActorOnly(<UpgradePremiumPage />) },
      { path: 'premium/payment-result', element: premiumActorOnly(<PaymentResultPage />) },
      { path: 'admin/dashboard', element: adminOnly(<AdminDashboardPage />) },
      { path: 'admin/users', element: adminOnly(<AdminUsersPage />) },
      { path: 'admin/users/:id', element: adminOnly(<AdminUserDetailPage />) },
      { path: 'admin/resources', element: adminOnly(<ResourceManagementPage />) },
      { path: 'admin/system-status', element: adminOnly(<SystemStatusPage />) },
      { path: 'notifications', element: authenticatedOnly(<NotificationsPage />) },
      { path: 'access-denied', element: <AccessDeniedPage /> },
      { path: 'not-found', element: <NotFoundPage /> },
      { path: '*', element: <Navigate to='/not-found' replace /> },
    ],
  },
]);
